[component.intercepted]
uri = "factory:logging-greeter-factory"
imports = ["greeter", "logger"]

[component.greeter]
uri = "./lib/hello.wasm"

[component.logger]
uri = "./lib/wasi-logging-to-stdout.wasm"
imports = ["wasip2"]

[component.logging-greeter-factory]
uri = "./lib/logging-interceptor-factory.wasm"
imports = ["loader"]
config.target = "hello.wasm"

[component.loader]
uri = "./lib/filesystem-loader.wasm"
imports = ["filesystem"]

[capability.filesystem]
type = "wasi:filesystem"

[[capability.filesystem.preopens]]
host = "./lib"
guest = "/lib"
perms = "read-only"

[capability.wasip2]
type = "wasi:p2"
